name: "My action"
description: "Test my action"

inputs:
  message:
    description: "The message to print"
    required: true
    default: "Hola"
  redis:
    image: redis
    ports:
      - 6379:6379

runs:
  using: "composite"
  steps:
    - name: Hola mundo
      run: echo "Hola ${{ inputs.message}}"
      shell: bash