name: Ejemplo de Composite Action

on: [push]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set environment variable
        run: echo "MY_VAR=Mi variable de entorno prueba" >> $GITHUB_ENV
        
      - name: Test
        run: echo "Valor: ${{ env.MY_VAR }}"
